[workspace]
members = [
    "ontio-std",
    "ontio-codegen",
    "ontio-bump-alloc",
    "examples",
    "examples/token",
    "examples/token-zero-copy",
    "examples/token-codegen",
    "examples/oep5token",
    "examples/oep8token",
    "examples/apitest",
    "examples/helloworld",
    "examples/red-envlope",
    "examples/wasm-call-wasm"
]

[profile.release]
panic = "abort"
lto = true
debug = true
opt-level = "s"

